name: Desplegar Pelican a GitHub Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Instalar uv
        uses: astral-sh/setup-uv@v3

      - name: Configurar entorno con uv
        run: uv sync

      - name: Compilar sitio con Pelican para producción
        run: uv run pelican content -s publishconf.py

      - name: Cargar artefacto de Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'output'

      - name: Publicar en GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4